# Generated by Django 4.0.4 on 2022-06-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['apellido', 'nombre']},
        ),
        migrations.AlterField(
            model_name='autor',
            name='image',
            field=models.ImageField(null=True, upload_to='catalogo/upload/img'),
        ),
    ]
