# Generated by Django 4.0.4 on 2022-06-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_customuser_latitude_alter_customuser_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
