# Generated by Django 4.0.4 on 2022-07-03 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejemplar',
            options={'ordering': ['libro', 'fechaDevolucion'], 'permissions': (('can_reserve_a_copy', 'Puede reservar ejemplar'), ('can_cancel_reservation', 'Puede cancelar reserva'))},
        ),
    ]
