# Generated by Django 4.0.4 on 2022-06-07 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_alter_autor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['-id', 'apellido', 'nombre']},
        ),
    ]
