# Generated by Django 4.0.4 on 2022-06-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_alter_autor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='catalogo/upload/img'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='image',
            field=models.ImageField(default='catalogo/img/default-libro.jpg', upload_to='images'),
        ),
    ]
