# Generated by Django 4.0.4 on 2022-06-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_alter_libro_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='POI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('lng', models.FloatField()),
                ('lat', models.FloatField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='ejemplar',
            options={'ordering': ['libro', 'fechaDevolucion']},
        ),
        migrations.AlterField(
            model_name='autor',
            name='image',
            field=models.ImageField(null=True, upload_to='catalogo/upload/img'),
        ),
    ]
