# Generated by Django 4.0.4 on 2022-06-24 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_alter_autor_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejemplar',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='libro',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
