# Generated by Django 4.0.4 on 2022-06-24 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_alter_ejemplar_options_alter_libro_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
