# Generated by Django 4.0.4 on 2022-06-24 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0010_alter_libro_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='image',
            field=models.ImageField(default='catalogo/upload/img/default-libro.jpg', upload_to='images'),
        ),
    ]
