# Generated by Django 4.0.4 on 2022-06-26 23:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0012_alter_ejemplar_options_alter_ejemplar_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejemplar',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='ID único para este libro particular en toda la biblioteca', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='libro',
            name='genero',
            field=models.ManyToManyField(help_text='Seleccione un género (o varios) para el libro', to='catalogo.genero'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='image',
            field=models.ImageField(default='catalogo/upload/img/default-libro.jpg', upload_to='catalogo/upload/img'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.CharField(help_text='13 Caracteres (<a href="https://www.isbninternational.org/content/what-isbn">ISBN number</a>)', max_length=13, verbose_name='ISBN'),
        ),
    ]
