# Generated by Django 4.0.4 on 2022-06-27 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0014_ejemplar_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejemplar',
            options={'ordering': ['libro', 'fechaDevolucion'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
