# Generated by Django 4.0.4 on 2022-06-27 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0016_alter_ejemplar_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejemplar',
            options={'ordering': ['libro', 'fechaDevolucion']},
        ),
    ]
