# Generated by Django 4.0.4 on 2022-06-28 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0018_alter_ejemplar_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejemplar',
            options={'ordering': ['libro', 'fechaDevolucion'], 'permissions': (('can_view_my_loans', 'Puedo ver mis préstamos'),)},
        ),
    ]
